version: '3.9'

services:
  db:
    image: postgres
    container_name: db-container
    volumes:
      - ./sql_dump:/docker-entrypoint-initdb.d
      - ./psql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=genericMessages
      - POSTGRES_USER=prueba
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  whatsapp_generic_messages:
    build: ./whatsapp_generic_messages
    container_name: backend-container
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./whatsapp_generic_messages:/whatsapp_generic_messages
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    
  generic_messages_vue:
    build: ./generic_messages_vue
    container_name: frontend-container
    command: npm run dev -- --host
    volumes:
      - ./generic_messages_vue:/generic_messages_vue
      - /generic_messages_vue/node_modules
    ports:
      - 5173:5173
    depends_on:
      - whatsapp_generic_messages