# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /whatsapp_generic_messages
COPY requirements.txt /whatsapp_generic_messages/
RUN pip install -r requirements.txt
COPY . /whatsapp_generic_messages/